[package]
name = "blockfrost"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3.17"
reqwest = { version = "0.11.4", features = ["multipart"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"

# Used in examples/
[dev-dependencies]
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
